### ISSUE TITLE
feat: Hover could contain more infomation

### ISSUE THREAD

**Issue by cutecutecat** [tensorchord/envd-lsp#35]
## Description
When we turn to `Python` extension Hover info, it would display `Args` and `Returns`:
![image](https://user-images.githubusercontent.com/19801166/215239420-a2872afb-760a-4801-a012-2ec0f25e1658.png)
While `envd` Hover only display documents, likes:
![image](https://user-images.githubusercontent.com/19801166/215239501-de20150d-eaa9-484d-803d-04b279dc93b6.png)

We have description of arguments either, we could display them like `Python` extension.
ref: https://envd.tensorchord.ai/api/starlark/v0/global.html

## How to fix
This is by inherited `Hover` from starlark use `plaintext` to display, it drops arguments/returns from docstring.
https://github.com/tilt-dev/starlark-lsp/blob/c0c1958f8166f93abfde9f5d3ddbf0d66e405730/pkg/query/signature.go#L72

We could provide a Markdown model and insert arguments and returns to it.

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by lalawuu** [comment]
Happy New Year. It seems that a good idea.

**Comment by gaocegege** [comment]
Great idea.

Do we need to update the API doc or something else in envd?

**Comment by cutecutecat** [comment]
> Great idea.
> 
> Do we need to update the API doc or something else in envd?

I think this work could be restricted at `envd-lsp`, as we has a full-featured document already. 

However, the related functions are called deeply at `starlark-lsp`. It might be impossible to overwrite that procedure without a huge code copy. That's not we want.

It might be better to contribute this feature to `starlark-lsp` project, and fetch it from upgrade dependency. I would take some time on it.

**Comment by cutecutecat** [comment]
> Great idea.
> 
> Do we need to update the API doc or something else in envd?

Oh, now I found it that we really need to update the API.

**Comment by cutecutecat** [comment]
> Great idea.
> 
> Do we need to update the API doc or something else in envd?

Now I found it that we really need to update the API.
