### ISSUE TITLE
chore: Update envd lsp automatically

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd-lsp#7]
## Description

---

**Message from the maintainers**:

Love this enhancement proposal? Give it a 👍. We prioritise the proposals with the most 👍.

**Comment by cutecutecat** [comment]
I will update the dependecy of envd at envd-lsp to v0.1.0, v0.2.0, v0.2.1, v0.2.2, v0.2.3, v0.2.4 at several PR, and push a tag for each. Then use a dependabot to keep the version up to date.
## Steps
- [x] Update envd dependecy to v0.2.0
- [x] Update envd dependecy to v0.2.2
- [x] Update envd dependecy to v0.2.3
- [x] Update envd dependecy to v0.2.4
- [ ] Deploy an dependabot
- [ ] Deploy a Github action for auto push tag
